language: node_js
node_js:
- lts/*
cache: yarn
notifications:
  slack: feinwaru:6x5Uv4tO4l1GEKsNh8F02Y9R
jobs:
  include:
  - stage: Tests
    install:
    - cd ui
    - yarn
    name: ESLint
    script:
    - yarn lint
  - install:
    - cd ui
    - yarn
    script:
    - yarn test
    name: Jest
  - stage: deploy
    name: Deploy
    install: echo $KEY >> $HOME/.ssh/known_hosts
    provider: script
    skip_cleanup: true
    before_script:
    - sudo apt install sshpass -y
    - echo -e "Host $IP\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    script:
    - sshpass -p $PASS rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/ui pi@$IP:sppd/ui
    on:
      branch: develop
before_install:
- openssl aes-256-cbc -K $encrypted_271ed4c32e6c_key -iv $encrypted_271ed4c32e6c_iv
  -in deploy_rsa.enc -out deploy_rsa -d
before_deploy:
- openssl aes-256-cbc -K $encrypted_271ed4c32e6c_key -iv $encrypted_271ed4c32e6c_iv
  -in travis_rsa.enc -out /tmp/travis_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/travis_rsa
- ssh-add /tmp/travis_rsa
