language: node_js
node_js:
- lts/*
cache: yarn
before_install:
- openssl aes-256-cbc -K $encrypted_83deb73f5baa_key -iv $encrypted_83deb73f5baa_iv
  -in ./.travis/travis.enc -out ../travis -d
notifications:
  slack: feinwaru:6x5Uv4tO4l1GEKsNh8F02Y9R
jobs:
  include:
    - stage: "Tests"
      install:
        - cd ui
        - yarn               # naming the Tests stage
      name: "ESLint"            # names the first Tests stage job
      script:
        - yarn lint
    - install:
        - cd ui
        - yarn 
      script: 
        - yarn test
      name: "Jest"     # names the second Tests stage job
    - stage: deploy
      name: "Deploy"
      if: branch = develop # qa environment
      script: bash deploy.sh