language: node_js
node_js:
- lts/*
cache: yarn
notifications:
  slack: feinwaru:6x5Uv4tO4l1GEKsNh8F02Y9R
before_install:
- sudo apt-get install -y sshpass
install:
- cd ui
- yarn
before_script:
- echo -e "Host $IP\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script:
- yarn lint
- yarn test
- cd ..
before_deploy:
- openssl aes-256-cbc -K $encrypted_271ed4c32e6c_key -iv $encrypted_271ed4c32e6c_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: sshpass -p $PASS rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/ui pi@$IP:sppd
  on:
    branch: develop
