language: node_js
node_js:
- lts/*
cache: 
yarn: true
before_install:
- openssl aes-256-cbc -K $encrypted_271ed4c32e6c_key -iv $encrypted_271ed4c32e6c_iv
  -in .travis/travis.enc -out travis -d
notifications:
  slack: feinwaru:6x5Uv4tO4l1GEKsNh8F02Y9R
install:
- cd ui
- yarn
- yarn lint
- yarn test
script:
- npx webpack --config webpack.dev.js
after_success: 
after_failure: 
