language: node_js
node_js:
- lts/*
cache: yarn
addons:
  ssh_known_hosts: $IP
notifications:
  slack: feinwaru:6x5Uv4tO4l1GEKsNh8F02Y9R
jobs:
  include:
  - stage: Tests
    install:
    - cd ui
    - yarn
    name: ESLint
    script:
    - yarn lint
  - install:
    - cd ui
    - yarn
    script:
    - yarn test
    name: Jest
  - stage: deploy
    name: Deploy
    provider: script
    skip_cleanup: true
    script:
    - if [ -z "`ssh-keygen -F $IP`" ]; then ssh-keyscan -H $IP >> ~/.ssh/known_hosts fi
    - rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/ui git@$IP:sppd/ui
    on:
      branch: develop
before_install:
- openssl aes-256-cbc -K $encrypted_96af6502cf30_key -iv $encrypted_96af6502cf30_iv -in travis_rsa.enc -out travis_rsa -d
before_deploy:
- openssl aes-256-cbc -K $encrypted_96af6502cf30_key -iv $encrypted_96af6502cf30_iv -in travis_rsa.enc -out /tmp/travis_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/travis_rsa
- ssh-add /tmp/travis_rsa
