apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-deployment"
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 1
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-deployment"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-deployment"
      annotations:
        # set automatically by github actions
        sha: {{ .Values.sha }}
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: "{{ .Release.Name }}-deployment"
        image: docker.pkg.github.com/{{ .Values.github }}/{{ .Release.Name }}/{{ .Release.Name }}:{{ .Values.branch }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.port }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.port }}
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
        env:
        - name: WEBSERVER_PORT
          valueFrom:
            configMapKeyRef:
              key: WEBSERVER_PORT
              name: "{{ .Release.Name }}-config"
